all:
  configuration:
    communes:
      "06158": "VILLARS-SUR-VAR",
      "13002": "ALLAUCH",
      "13015": "BOUC-BEL-AIR",
      "13023": "CEYRESTE",
      "13025": "CHATEAUNEUF-LE-ROUGE",
      "13028": "CIOTAT",
      "13030": "CUGES-LES-PINS",
      "13060": "MEYREUIL",
      "13072": "PEYNIER",
      "13079": "PUYLOUBIER",
      "13085": "ROQUEFORT-LA-BEDOULE",
      "13087": "ROUSSET",
      "13109": "THOLONET",
      "13110": "TRETS",
      "83004": "ARCS",
      "83008": "BAGNOLS-EN-FORET",
      "83016": "BEAUSSET",
      "83018": "BESSE-SUR-ISSOLE",
      "83019": "BORMES-LES-MIMOSAS",
      "83026": "CABASSE",
      "83027": "CADIERE-D'AZUR",
      "83028": "CALLAS",
      "83031": "CANNET-DES-MAURES",
      "83032": "CARCES",
      "83033": "CARNOULES",
      "83034": "CARQUEIRANNE",
      "83035": "CASTELLET",
      "83042": "COGOLIN",
      "83043": "COLLOBRIERES",
      "83045": "CORRENS",
      "83046": "COTIGNAC",
      "83047": "CRAU",
      "83048": "CROIX-VALMER",
      "83049": "CUERS",
      "83050": "DRAGUIGNAN",
      "83051": "ENTRECASTEAUX",
      "83053": "EVENOS",
      "83054": "FARLEDE",
      "83056": "FIGANIERES",
      "83057": "FLASSANS-SUR-ISSOLE",
      "83058": "FLAYOSC",
      "83061": "FREJUS",
      "83062": "GARDE",
      "83063": "GARDE-FREINET",
      "83065": "GASSIN",
      "83067": "GONFARON",
      "83068": "GRIMAUD",
      "83069": "HYERES",
      "83071": "LONDE-LES-MAURES",
      "83072": "LORGUES",
      "83073": "LUC",
      "83075": "MAYONS",
      "83079": "MOLE",
      "83083": "MONTFORT-SUR-ARGENS",
      "83085": "MOTTE",
      "83086": "MUY",
      "83091": "PIERREFEU-DU-VAR",
      "83092": "PIGNANS",
      "83094": "PLAN-DE-LA-TOUR",
      "83096": "POURCIEUX",
      "83097": "POURRIERES",
      "83098": "PRADET",
      "83099": "PUGET-SUR-ARGENS",
      "83100": "PUGET-VILLE",
      "83101": "RAMATUELLE",
      "83107": "ROQUEBRUNE-SUR-ARGENS",
      "83112": "SAINT-CYR-SUR-MER",
      "83115": "SAINTE-MAXIME",
      "83117": "SAINT-PAUL-EN-FORET",
      "83118": "SAINT-RAPHAEL",
      "83119": "SAINT-TROPEZ",
      "83124": "SEILLANS",
      "83129": "SIX-FOURS-LES-PLAGES",
      "83130": "SOLLIES-PONT",
      "83134": "TARADEAU",
      "83136": "THORONET",
      "83141": "TRANS-EN-PROVENCE",
      "83148": "VIDAUBAN",
      "83154": "SAINT-ANTONIN-DU-VAR"
