all:
  configuration:
    drev:
      prelevements: false
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: true
      habilitation_inao: true
      cgu: true
